version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development
      - PORT=3333
      - DATABASE_URL=sqlite:./data/news.db
    volumes:
      - ./data:/app/data
      - ./apps/api/src:/app/src:ro
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3333/healthz', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3333
    volumes:
      - ./apps/frontend/src:/app/src:ro
      - ./apps/frontend/public:/app/public:ro
    depends_on:
      - api

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=globalnews
      - POSTGRES_USER=globalnews
      - POSTGRES_PASSWORD=dev_password_change_in_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/api/src/database/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U globalnews -d globalnews"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  default:
    name: globalnews_network