# Development overrides for docker-compose
# This file is automatically loaded by docker-compose

services:
  api:
    volumes:
      - ./apps/api:/app/apps/api
      - ./packages:/app/packages
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]

  frontend:
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]