version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3333:3333"
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
      - PORT=3333
      - DATABASE_URL=postgresql://globalnews:globalnews123@db:5432/globalnews
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=globalnews
      - DB_PASSWORD=globalnews123
      - DB_NAME=globalnews
      - POSTGRES_PASSWORD=globalnews123
      - LLM_PROVIDER=ollama
      - LLM_MODEL=mistral
      - LLM_MOCK_IN_DEV=true
    volumes:
      - api_data:/app/data
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3333/healthz', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - api
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=globalnews
      - POSTGRES_USER=globalnews
      - POSTGRES_PASSWORD=globalnews123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U globalnews -d globalnews"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
      - frontend
    restart: unless-stopped

volumes:
  postgres_data:
  api_data:

networks:
  default:
    name: globalnews_production